const L1="Recommended College Programs",L2="Possible Careers";
// [letter,title,cluster,description,programs,careers,why,icon,color,label1,label2]
const AC=[
["A","The Creative Communicator","Arts, Social Sciences, and Humanities","You are interested in people, culture, communication, creativity, and ideas. You enjoy expressing yourself and understanding different perspectives.","BA Communication|BA Psychology|BA Political Science|BA Sociology|BA English|Bachelor of Education|Fine Arts|Multimedia Arts","Teacher|Writer|Journalist|Psychologist|Social Worker|Communication Specialist|Artist|Content Creator","Your answers show an interest in communication, creativity, people, culture, and society.","","#16a34a"],
["B","The Future Entrepreneur","Business and Entrepreneurship","You enjoy planning, organizing, making decisions, and turning ideas into opportunities. You are interested in business, money, marketing, leadership, and entrepreneurship.","BS Business Administration|BS Entrepreneurship|BS Accountancy|BS Marketing|BS Management|BS Economics|BS Finance","Entrepreneur|Business Manager|Accountant|Marketing Specialist|Financial Analyst|Sales Manager|Business Consultant","Your answers show strong interest in business, leadership, planning, money, and entrepreneurship.","","#eab308"],
["C","The Analytical Innovator","Science, Technology, Engineering, and Mathematics","You enjoy solving problems, analyzing information, and understanding how things work. You like challenges involving logic, mathematics, science, research, and technology.","BS Computer Science|BS Information Technology|BS Information Systems|BS Engineering|BS Mathematics|BS Biology|BS Chemistry|BS Physics|BS Data Science","Software Developer|Engineer|Data Analyst|Programmer|Scientist|Researcher|IT Specialist|Systems Analyst","Your answers show strong interest in science, mathematics, technology, research, and logical problem-solving.","","#dc2626"],
["D","The Active Wellbeing Leader","Sports, Health, and Wellness","You enjoy staying active, working with others, and learning about health, fitness, sports, and wellness. You like activities where you can participate, motivate others, and promote healthy living.","BS Physical Education|BS Exercise and Sports Science|BS Sports Science|BS Nutrition and Dietetics|BS Physical Therapy|BS Occupational Therapy|BS Nursing","Coach|Fitness Professional|Sports Instructor|Physical Therapist|Nutritionist/Dietitian|Wellness Professional|Sports Organizer","Your answers show strong interest in physical activity, sports, health, teamwork, and wellness.","","#0891b2"],
["E","The Real-World Explorer","Field Experience","You learn best when you can apply knowledge to real situations. You enjoy hands-on activities, practical tasks, workplace experiences, and projects that connect learning to the real world.","Workplace exposure|Community projects|Industry-related activities|Practical research|Career exploration|Work-based learning|Design and innovation projects","Business|Technology|Education|Hospitality|Community Services|Creative Industries","Your answers show that you value hands-on learning, practical skills, real-world experience, and career preparation.","","#7c3aed","Possible Experiences","Possible Career Directions"]
];
const TC=[
["A","The Tech Innovator","ICT and Digital Technology","You enjoy understanding technology, solving technical problems, and creating digital solutions. You are curious about computers, software, programming, websites, and digital systems.","BS Information Technology|BS Computer Science|BS Information Systems|BS Computer Engineering|BS Cybersecurity|BS Data Science|BS Multimedia Arts","Software Developer|Web Developer|IT Specialist|Programmer|Systems Analyst|Network Technician|Cybersecurity Specialist|Data Analyst","Your answers show strong interest in technology, computers, programming, problem-solving, and digital innovation.","","#2563eb"],
["B","The Creative Technologist","Creative Arts and Design Technologies","You enjoy using technology to create visual and digital content. You like graphic design, video editing, animation, photography, and multimedia production.","BS Multimedia Arts|Bachelor of Fine Arts|BA Communication|BS Digital Media|BS Entertainment and Multimedia Computing|BS Information Technology|Graphic Design","Graphic Designer|Video Editor|Multimedia Artist|Animator|UI/UX Designer|Photographer|Content Creator|Digital Artist","Your answers show strong interest in creativity, design, digital tools, visual communication, and technology.","","#db2777"],
["C","The Practical Organizer","Business, Data, and Technology Support","You enjoy organizing tasks, managing projects, and using technology to make work easier and more efficient. You may be interested in data, digital systems, and practical technology applications.","BS Information Systems|BS Business Administration|BS Information Technology|BS Business Analytics|BS Management|BS Entrepreneurship","IT Support Specialist|Data Analyst|Project Coordinator|Systems Administrator|Business Analyst|Technology Project Manager|Business Owner","Your answers show strong interest in organization, practical technology, data, planning, and project management.","","#ca8a04"],
["D","The People-Focused Technologist","Technology and Service Applications","You enjoy using technology to help people and improve everyday experiences. You may enjoy communication, teamwork, customer support, and applying technology in practical situations.","BS Information Technology|BS Information Systems|BS Hospitality Management|BS Tourism Management|BA Communication|BS Business Administration|Bachelor of Education","IT Support Specialist|Technical Support Representative|Technology Trainer|Service Coordinator|Digital Support Specialist|Customer Support Specialist","Your answers show that you value people, communication, teamwork, service, and the practical use of technology.","","#059669"],
["E","The Hands-On Professional","Practical Skills and Work-Based Learning","You learn best by doing. You enjoy practical activities, working with tools or equipment, completing real-world tasks, and gaining experience through hands-on projects.","BS Industrial Technology|BS Information Technology|BS Hospitality Management|BS Automotive Technology|BS Food Technology|BS Agriculture|BS Entrepreneurship","Technical Specialist|IT Support Specialist|Technician|Hospitality Professional|Automotive Technician|Food Technologist|Agricultural Technician|Entrepreneur","Your answers show strong interest in hands-on learning, practical skills, real-world tasks, workplace experience, and applying knowledge.","","#ea580c"]
];
const SETS={A:AC,T:TC};
const $=id=>document.getElementById(id);
function go(id){$(id).scrollIntoView({behavior:'smooth'})}
function show(k){
 $('tA').className='tab'+(k=='A'?' on':'');$('tT').className='tab'+(k=='T'?' on':'');
 $('cards').innerHTML=SETS[k].map((r,i)=>`<div class="card" style="--c:${r[8]}" onclick="openM('${k}',${i})"><div class="ic"></div><h3>${r[1]}</h3><div class="cl">${r[2]}</div><p>${r[3].split('. ')[0]}.</p><span class="more">View Details →</span></div>`).join('');
}
function tags(s,c){return `<div class="tags">${s.split('|').map(x=>`<span class="tag ${c||''}">${x}</span>`).join('')}</div>`}
function openM(k,i){
 const r=SETS[k][i];
 $('mbody').innerHTML=`<div class="mh"><h2 style="color:#fff;text-align:left;margin:0">${r[1]}</h2><p>${r[2]}</p></div><div class="mb"><p>${r[3]}</p><h4>${r[9]||L1}</h4>${tags(r[4],'g')}<h4>${r[10]||L2}</h4>${tags(r[5])}<h4>Why this fits you</h4><p>${r[6]}</p></div>`;
 $('modal').style.display='block';
}
function closeM(){$('modal').style.display='none'}
window.onclick=e=>{if(e.target==$('modal'))closeM()};

// Techpro Strand Quiz
const QT=[
["When a new gadget or software comes out, what is your first reaction?",["I want to learn how it works, and possibly take it apart.","I want to think of ways to use it and what I could make with it.","I wait for it to become popular before trying it out.","I don't really care about new technology.","I want to set it up and try it out hands-on right away."]],
["How do you feel about solving challenging or difficult puzzles?",["I love logic puzzles, they are fun!","I would like to solve them, if they are relevant to what I am working on right now.","I don't enjoy them, unless it is mandatory.","I find them frustrating and annoying.","I enjoy practical challenges, like fixing something that's actually broken."]],
["What do you think would be the most fun to do?",["Coding a simple program or website.","Graphic design or video editing.","Entering and organizing information in a computer database.","Writing an essay or story.","Assembling, repairing, or setting up computers and equipment."]],
["When working on a group project, what do you think would be the best role for you?",["The one who works with the computer programs or websites.","The one who designs or comes up with new ideas.","The one who helps organize the project and keeps everyone on track.","The one who presents the project to the class.","The one who does the hands-on work, like setting up and testing equipment."]],
["What do you think about being patient when working with technology (or other systems), when things aren't going right?",["I am always patient, and I work at it until I figure it out.","I am somewhat patient, but I may try a few things first, and then ask for help.","I am not very patient, and it can be hard to find solutions.","I give up easily, and ask for help right away.","I stay patient when I can test fixes hands-on and learn by trying."]],
["What kind of work environment do you prefer?",["Quiet, where I can concentrate on the computer.","Collaborative, where I can work with other people.","Organized, where everything has a place and a purpose.","Dynamic, where nothing is ever dull or boring.","Practical, where I can work with tools, equipment, and real tasks."]],
["What subject do you think you would be the most interested in?",["Computer Science or IT (information technology).","Math or Physics.","Art or Design.","History or Literature.","Industrial or technical skills training, such as electronics or computer repair."]],
["How do you like to learn?",["By doing hands-on activities.","By watching videos or learning online.","By reading books or documents.","By listening to a teacher talk about it.","By doing real tasks in a workplace or through on-the-job training."]],
["What would your ideal career be?",["I would like to be a software developer or network engineer.","I would like to work in graphic design, animation or video editing.","I want to manage technology projects, or maybe even start my own business.","I'm not sure exactly, but it should incorporate helping other people.","I would like to be a technician or technical specialist, such as in IT support, automotive, or food technology."]],
["How important is it for you to keep up to date with new technology?",["Very important, I like to know about all of the latest news.","It is somewhat important to know about, but I don't need to focus on it.","Not really important, I only care about it if it affects me somehow.","Not at all important to me.","It matters when it helps me do practical work better, like new tools and equipment."]]
];
const QA=[
["Which activity would you enjoy the most?",["Writing, creating art, discussing culture, or expressing ideas","Planning a business, selling products, or managing money","Solving math problems, doing experiments, or exploring how things work","Playing sports, exercising, or learning about health and fitness","Learning through hands-on activities, real-world tasks, or workplace experiences"]],
["What kind of problem do you enjoy solving?",["Problems involving people, society, culture, or communication","Problems involving money, business, customers, or organizations","Problems involving science, mathematics, technology, or logical thinking","Problems involving physical performance, health, or wellness","Practical problems that require you to apply what you learned in a real situation"]],
["If you could choose a school project, which would you prefer?",["Create a story, artwork, presentation, or research about society and culture","Create a business plan or plan how to market a product","Conduct a scientific experiment or solve a technical problem","Organize a sports, fitness, or wellness activity","Complete a hands-on project connected to an actual workplace or community situation"]],
["Which skill would you most like to develop?",["Communication, creativity, writing, or understanding people","Leadership, entrepreneurship, management, or decision-making","Critical thinking, mathematics, research, or problem-solving","Physical fitness, teamwork, movement, or health awareness","Practical skills, workplace readiness, responsibility, or applying knowledge"]],
["Which topic interests you the most?",["Literature, history, culture, society, communication, or the arts","Business, marketing, finance, entrepreneurship, or management","Biology, chemistry, physics, mathematics, or scientific ideas","Sports, exercise, nutrition, physical education, or wellness","Career preparation, workplace skills, community projects, or real-world applications"]],
["What type of activity makes you feel most engaged?",["Discussing ideas, creating something, or communicating with others","Organizing people, planning projects, or developing business ideas","Investigating questions, analyzing information, or finding solutions","Moving, exercising, competing, or helping others become healthier","Doing tasks where you can practice skills and see how they work in real situations"]],
["Which role would you most likely enjoy?",["Writer, artist, researcher, communicator, or community worker","Entrepreneur, manager, marketer, or business owner","Scientist, engineer, researcher, or other STEM-related professional","Coach, fitness professional, sports organizer, or wellness advocate","Intern, trainee, project assistant, or someone gaining experience in a real work setting"]],
["When working in a group, what would you naturally contribute?",["Ideas, creativity, writing, and communication","Leadership, planning, organization, and decision-making","Research, analysis, calculations, and problem-solving","Teamwork, motivation, and active participation","Practical skills, task completion, and applying what the group learned"]],
["Which statement sounds most like you?",["\u201cI enjoy understanding people and expressing ideas creatively.\u201d","\u201cI enjoy turning ideas into projects, products, or business opportunities.\u201d","\u201cI enjoy understanding how things work and finding logical solutions.\u201d","\u201cI enjoy staying active and learning about health, sports, and wellness.\u201d","\u201cI learn best when I can practice skills and connect learning to real situations.\u201d"]],
["What would you most like your SHS experience to prepare you for?",["Further study or careers related to people, society, communication, and the arts","Further study or careers related to business, management, and entrepreneurship","Further study or careers related to science, technology, engineering, and mathematics","Further study or careers related to sports, health, fitness, and wellness","Further study, employment, or career opportunities through practical and real-world experience"]]
];
const Q=QA.concat(QT);
const LET="ABCDE";let qi=0,ans=[];
function render(){
 $('qt').innerHTML=`<small style="display:block;color:#667eea;margin-bottom:.4rem">${qi<10?'Part 1: Academic':'Part 2: TechPro'}</small>`+Q[qi][0];
 $('opts').innerHTML=Q[qi][1].map((o,i)=>`<div class="opt${ans[qi]===i?' sel':''}" onclick="pick(${i})"><b>${LET[i]}.</b><span>${o}</span></div>`).join('');
 $('cur').textContent=qi+1;$('tot').textContent=Q.length;
 $('prog').style.width=((qi+1)/Q.length*100)+'%';
 $('prev').disabled=qi==0;
 const last=qi==Q.length-1,has=ans[qi]!==undefined;
 $('next').style.display=last?'none':'';$('sub').style.display=last?'':'none';
 $('next').disabled=!has;$('sub').disabled=!has;
}
function pick(i){ans[qi]=i;render()}
$('prev').onclick=()=>{qi--;render()};
$('next').onclick=()=>{qi++;render()};
$('sub').onclick=()=>{
 const grp=(from,set,title)=>{
  const n=[0,0,0,0,0];ans.slice(from,from+10).forEach(a=>n[a]++);
  const order=n.map((c,i)=>[c,i]).filter(x=>x[0]>0).sort((a,b)=>b[0]-a[0]||a[1]-b[1]);
  return `<h2 style="font-size:1.8rem;margin:2rem 0 1.5rem">${title}</h2>`+order.map(([c,i],idx)=>{const r=set[i];return `<div class="match${idx==0?' top':''}"><div class="mhd"><h3>${LET[i]}: ${r[1]}${idx==0?' ':''}</h3><span class="pct">${c*10}%</span></div><p><i>${r[2]}</i></p><p>${r[3]}</p><h4 style="margin:.8rem 0 .4rem">${r[9]||L1}</h4>${tags(r[4],'g')}<h4 style="margin:.8rem 0 .4rem">${r[10]||L2}</h4>${tags(r[5])}<p style="margin-top:.8rem"><b>Why this fits you:</b> ${r[6]}</p></div>`}).join('');
 };
 $('rc').innerHTML=grp(0,AC,'Academic Results')+grp(10,TC,'TechPro Results');
 $('results').style.display='block';go('results');
};
function retake(){qi=0;ans=[];render();$('results').style.display='none';go('quiz')}
show('A');render();